[terminal.shell]
program = "/bin/zsh"
args = ["--login"]

[window]
opacity=0.7


[font]
normal.family = "IosevkaTerm NerdFont"
bold.family = "IosevkaTerm NerdFont"
italic.family = "IosevkaTerm NerdFont"
bold_italic.family = "IosevkaTerm NerdFont"

size = 16.0
