#!/bin/bash

# 先截圖，存到暫存檔
tmpfile=$(mktemp --suffix=.png)
grim -g "$(slurp)" "$tmpfile"

# 用 rofi 顯示選單
choice=$(echo -e "Copy\nSave" | rofi -dmenu -p "Screenshot Action")

if [ "$choice" == "Copy" ]; then
  wl-copy < "$tmpfile"
  notify-send "Screenshot copied to clipboard!"
elif [ "$choice" == "Save" ]; then
  filename="$HOME/Pictures/Screenshots/screenshot_$(date +'%Y-%m-%d_%H-%M-%S').png"
  mkdir -p "$HOME/Pictures/Screenshots"
  cp "$tmpfile" "$filename"
  notify-send "Screenshot saved to $filename"
fi

rm "$tmpfile"
