#alacritty.toml
[window]
opacity = 0.7
decorations = "full"

[window.padding]
x = 8
y = 8

[font]
size = 20.0

[font.normal]
family = "Cascadia Code"
style = "Regular"

[terminal.shell]
program = "/home/zenith/.nix-profile/bin/zsh"
args = ["--login"]

